export class User {
    Matricule;
    Nom;
    Prenom;
    etat;
    idRole;
    email;
    password;
    photo
    constructor(
        Matricule,
        Nom,
        Prenom,
        etat,
        idRole,
        email,
        password,
        photo){
        this.Matricule=Matricule;
        this.Nom=Nom;
        this.Prenom=Prenom;
        this.etat=etat;
        this.idRole=idRole;
        this.email=email;
        this.password=password;
        this.photo=photo
    }
}